### ISSUE TITLE
Carregamento font awesome

### ISSUE THREAD

**Issue by flemej** [HXPHP/hxphp-facebook-social-login#1]
@brunosantoshx ,
Alguns ícones do font awesome não estão funcionando. O exemplo abaixo funciona perfeitamente:
'
$configs->env->development->menu->setMenus(array (
    'Home/bars' => '%baseURI%/home',
    'Cadastro/pencil' => array(
        'Usuários/users' => '%baseURI%/home',
        'Embalagens/square-o' => '%baseURI%/atualizacoes'
        ),
    'Log-out/arrow-right' => '%baseURI%/login/sair'
    ), 
    'administrator');
'
Se eu substituir o ícone do menu "Usuário" de "users' para "address-book-o", como abaixo, o ícone não aparece.
'
$configs->env->development->menu->setMenus(array (
    'Home/bars' => '%baseURI%/home',
    'Cadastro/pencil' => array(
        'Usuários/address-book-o' => '%baseURI%/home',
        'Embalagens/square-o' => '%baseURI%/atualizacoes'
        ),
    'Log-out/arrow-right' => '%baseURI%/login/sair'
    ), 
    'administrator');
'
Sabe o que pode ser?
Obrigado!

**Comment by brunosantoshx** [comment]
Olá @flemej, boa noite. Como vai?

O Font Awesome é constantemente atualizado, ou seja, para usar os novos ícones é preciso atualizar também a versão presente no framework.

Vou providenciar um PR com a nova versão, mas, sempre que precisar é só rodar o comando `bower install font-awesome`.

Forte abraço e sucesso sempre!
